# Docker Environment Variables
# build > args = Build-time Environment Variables, rebuild required on change of these. These remain in the image history so should not be used for secrets
# env_file = Runtime Environment Variables
# environment = Runtime Environment Variables with higher precedence than env_file
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # args:
      #   - NODE_ENV=development # Build-time environment variable
    container_name: balanced_app_dev
    env_file:
      - .env.development # Runtime environment variables
    # environment:
    #   # Runtime environment variables - these override env_file
    #   NODE_ENV: 'development'
    ports:
      - '3000:3000'
    # volumes:
    # Keep container versions of these directories to avoid permission issues
    # - node_modules_dev:/app/node_modules
    # - next_dev:/app/.next
    # Mount source code for development
    # - ./src:/app/src
    # - ./public:/app/public
    # - ./prisma:/app/prisma
    # Mount config files
    # - ./package.json:/app/package.json
    # - ./tsconfig.json:/app/tsconfig.json
    # - ./.env.development:/app/.env
    # Command to run when the container starts
    # command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    container_name: balanced_db_dev
    image: postgres:16-alpine
    restart: always # So any changes to the database are shown
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: balanced_dev
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    ports:
      - '${DB_PORT}:5432' # host:container
    volumes:
      # persist the database data between container restarts in dev
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  studio:
    container_name: balanced_studio_dev
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    command: sh -c "npx prisma studio --port 5555"
    ports:
      - '5555:5555'

volumes:
  db:
    name: balanced_postgres_dev_db
