# Docker Environment Variables
# build > args = Build-time Environment Variables, rebuild required on change of these. These remain in the image history so should not be used for secrets
# env_file = Runtime Environment Variables
# environment = Runtime Environment Variables with higher precedence than env_file
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: balanced_app_dev
    environment:
      # Runtime environment variables - these override env_file
      - CHOKIDAR_USEPOLLING=true # Polling for file changes
      - WATCHPACK_POLLING=true # Polling for file changes
    env_file:
      - .env.development # Runtime environment variables
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Mount the entire project directory
      - /app/node_modules # Keep container versions of these directories to avoid permission issues
      - /app/.next # Keep container versions of these directories to avoid permission issues
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    container_name: balanced_db_dev
    image: postgres:16-alpine
    restart: always # So any changes to the database are shown
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: balanced_dev
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    ports:
      - '${DB_PORT}:5432' # host:container
    volumes:
      # persist the database data between container restarts in dev
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  studio:
    container_name: balanced_studio_dev
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    command: sh -c "npx prisma studio --port 5555"
    ports:
      - '5555:5555'

volumes:
  db:
    name: balanced_postgres_dev_db
